lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', StudentDeleteView.as_view(), name='delete'),
]

students/models.py
import random
import uuid

from core.models import Person

from django.db import models

from faker import Faker

from groups.models import Group


class Student(Person):

    rating = models.SmallIntegerField(null=True, default=0)
    phone_number = models.CharField(max_length=64, null=True, blank=True)
    group = models.ForeignKey(to=Group, null=True, on_delete=models.SET_NULL, related_name='students')

    def __str__(self):
        return f'{super().__str__()}, {self.rating}'

    @staticmethod
    def create_student(student_count):
        fake = Faker()
        groups = list(Group.objects.all())

        for _ in range(int(student_count)):
            f_name = fake.first_name()
            l_name = fake.last_name()
            rating = random.randint(0, 100)
            uu_id = uuid.uuid4()
            group = random.choice(groups)

            Student.objects.create(first_name=f_name, last_name=l_name,
                                   rating=rating, uu_id=uu_id, group=group)

students/forms.py
from django import forms
from django.core.exceptions import ValidationError

from students.models import Student


class StudentsCreateForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'phone_number', 'group']

    def clean_phone_number(self):

        phone_number = self.cleaned_data['phone_number']

        if not phone_number:
            raise ValidationError('Enter phone number')
        if not phone_number.isnumeric():
            raise ValidationError('Enter correct phone number')

        return phone_number

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from students.forms import StudentsCreateForm
from students.models import Student
from students.utils import gen_password, parse_lenght


def hello(request):
    return HttpResponse('Hello from Django!')


def get_random(request):
    try:
        length = parse_lenght(request, 10)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)

    result = gen_password(length)

    return HttpResponse(result)


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'student-get.html'
    context_object_name = 'students'
    paginate_by = 6

    def get_queryset(self):
        """
        Функция осуществляет фильтрацию

        super().get_queryset() - наследование от базового класса

        self.request - в классе StudentListView есть доступ к request

        qr - список обьектов класса Student. Аналог записи Student.objects.all()
        """
        qr = super().get_queryset()
        request = self.request

        first_name = request.GET.get('first_name')
        last_name = request.GET.get('last_name')
        rating = request.GET.get('rating')

        if first_name:
            qr = qr.filter(first_name=first_name)
        if last_name:
            qr = qr.filter(last_name=last_name)
        if rating:
            qr = qr.filter(rating=rating)

        return qr


class StudentCreateView(LoginRequiredMixin, CreateView):
    """
    Класс реализует функционал создания студента

     UpdateView - встроенный класс Джанго, стандарная реализация создания.
        переменные задаются как написано в документации.
    """
    model = Student
    form_class = StudentsCreateForm
    success_url = reverse_lazy('students:list')
    template_name = 'student-create.html'


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    """
     Класс реализует функционал редактирования студента

     UpdateView - встроенный класс Джанго, стандарная реализация редактирования.
        переменные задаются как написано в документации.

     # get_object - возвращает студента по uu_id.
    """
    model = Student
    form_class = StudentsCreateForm
    success_url = reverse_lazy('students:list')
    template_name = 'student-edit.html'
    context_object_name = 'student'

    def get_object(self):
        """
        self - это обьект класса StudentUpdateView

        self.kwargs.get('uuid') - kwargs это словарь, get('uuid') функция возвращает значение ключа 'uuid'

        self.get_queryset() - возвращает объект модели. В данном случае по конкретному айдишнику.
        """

        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uu_id=uuid)


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('students:list')

    def get_object(self):
        """
        self - это обьект класса StudentDeleteView

        self.kwargs.get('uuid') - kwargs это словарь, get('uuid') функция возвращает значение ключа 'uuid'

        self.get_queryset() - возвращает объект модели. В данном случае по конкретному айдишнику.
        """

        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uu_id=uuid)

    def delete(self, request, *args, **kwargs):
        """
        Стандартный метод базового класса

        self.get_object() - Принимает один обьект из метода get_object, который я переопределил

        self.get_success_url() - подхватывает атрибут класса
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

students/templates/student-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h3>Create student</h3>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Create">
    </form>
{% endblock %}

students/templates/student-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h3>Edit student</h3>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Edit">
        <input formaction="{% url 'students:delete' student.uu_id %}" type="submit" value="Delete">
    </form>
{% endblock %}

students/templates/student-get.html
{% extends 'base.html' %}


{% block header %}
    <h3>Students</h3>
{% endblock %}

{% block content %}
    <form>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">First name</span>
          </div>
          <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon2">Last name</span>
          </div>
          <input name="Last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon3">Rating</span>
          </div>
          <input name="rating" type="number" class="form-control" placeholder="Enter rating" aria-label="Username" aria-describedby="basic-addon1">
        </div>

      <input type="submit" value="Search">
      <input formaction="{% url 'students:create' %}" type="submit" value="Create">

    </form>

    {% include 'includes/students-table.html' %}

    {% include 'includes/paginator.html' %}


{% endblock %}