lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import TeacherCreateView, TeacherListView, TeacherdeleteView, TeahcerUpdateView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', TeahcerUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', TeacherdeleteView.as_view(), name='delete'),
]

teachers/models.py
import uuid

from core.models import Person

from faker import Faker


class Teacher(Person):

    @staticmethod
    def create_teacher(teacher_count):
        fake = Faker()

        for _ in range(int(teacher_count)):
            f_name = fake.first_name()
            l_name = fake.last_name()
            uu_id = uuid.uuid4()

            Teacher.objects.create(first_name=f_name, last_name=l_name,
                                   uu_id=uu_id)

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherCreateForm(forms.ModelForm):
    class Meta():
        model = Teacher
        fields = ['first_name', 'last_name']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from teachers.models import Teacher

from .forms import TeacherCreateForm


class TeacherListView(LoginRequiredMixin, ListView):
    model = Teacher
    template_name = 'teacher-get.html'
    context_object_name = 'teachers'
    paginate_by = 6

    def get_queryset(self):
        """
        Функция осуществляет фильтрацию

        super().get_queryset() - наследование от базового класса. Аналог записи Teacher.objects.all()

        self.request - в классе TeacherListView есть доступ к request

        qr - список обьектов класса Teacher.
        """
        qr = super().get_queryset()
        request = self.request

        first_name = request.GET.get('first_name')
        last_name = request.GET.get('last_name')

        if first_name:
            qr = qr.filter(first_name=first_name)
        if last_name:
            qr = qr.filter(last_name=last_name)

        return qr


class TeacherCreateView(LoginRequiredMixin, CreateView):
    """
    Класс реализует функционал создания учителя

     UpdateView - встроенный класс Джанго, стандарная реализация создания.
        переменные задаются как написано в документации.
    """
    model = Teacher
    form_class = TeacherCreateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teacher-create.html'


class TeahcerUpdateView(UpdateView):
    """
         Класс реализует функционал редактирования учителей

         UpdateView - встроенный класс Джанго, стандарная реализация редактирования.
            переменные задаются как написано в документации.

         # get_object - возвращает учителя по uu_id.

         get_context_data - расширяет словарь context в функции render()

        """
    model = Teacher
    form_class = TeacherCreateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teacher-edit.html'
    context_object_name = 'teacher'

    def get_object(self):
        """
        self - это обьект класса TeacherUpdateView

        self.kwargs.get('uuid') - kwargs это словарь, get('uuid') функция возвращает значение ключа 'uuid'

        self.get_queryset() - возвращает объект модели. В данном случае по конкретному айдишнику.
        """

        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uu_id=uuid)

    def get_context_data(self, **kwargs):
        """
        ????  super().get_context_data(**kwargs) -- Не совсем понял как это работает ????
        """
        context = super().get_context_data(**kwargs)
        context['groups'] = self.get_object().groups.all()
        return context


class TeacherdeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list')

    def get_object(self):
        """
        self - это обьект класса TeacherDeleteView

        self.kwargs.get('uuid') - kwargs это словарь, get('uuid') функция возвращает значение ключа 'uuid'

        self.get_queryset() - возвращает объект модели. В данном случае по конкретному айдишнику.
        """

        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uu_id=uuid)

    def delete(self, request, *args, **kwargs):
        """
        Стандартный метод базового класса

        self.get_object() - Принимает один обьект из метода get_object, который я переопределил

        self.get_success_url() - подхватывает атрибут класса
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

teachers/templates/teacher-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h3>Create teacher</h3>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Create">
    </form>

{% endblock %}

teachers/templates/teacher-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
    <h3>Edit teacher</h3>
{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Edit">
        <input formaction="{% url 'teachers:delete' teacher.uu_id%}" type="submit" value="Delete">
    </form>

    {% include 'includes/groups-table.html' %}

{% endblock %}

teachers/templates/teacher-get.html
{% extends 'base.html' %}


{% block header %}
    <h3>Teachers</h3>
{% endblock %}


{% block content %}
    <form>
<div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">First name</span>
          </div>
          <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon2">Last name</span>
          </div>
          <input name="Last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
        </div>

      <input type="submit" value="Search">
      <input formaction="{% url 'teachers:create' %}" type="submit" value="Create">
    </form>

    <table class="table table-bordered">
          <tr>
            <th>Edit</th>
            <th>First name</th>
            <th>Last name</th>
          </tr>
        {% for teacher in teachers %}
            <tr>
                <td><a href="{% url 'teachers:edit' teacher.uu_id %}">EDIT</a></td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
            </tr>
        {% endfor %}
    </table>

    {% include 'includes/paginator.html' %}

{% endblock %}