accounts/urls.py
from accounts.views import AccountCreateView, AccountLoginView, AccountLogoutView, AccountUpdateView, PasswordUpdateView

from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', PasswordUpdateView.as_view(), name='password'),

]

core/urls.py
from core.views import index

from django.urls import path


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),

]

groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupListView, GroupUpdateView
app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create', GroupCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', GroupUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', GroupDeleteView.as_view(), name='delete'),

]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', StudentDeleteView.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Title</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
          crossorigin="anonymous">
</head>


<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:list' %}">Students<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'groups:list' %}">Groups</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'teachers:list' %}" >Teachers</a>
          </li>
        </ul>


        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <img src="{{ user.profile.image.url }}" width="40" height="40">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Registration</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
      </div>
  </div>
</nav>

<div class="container">

    {% include 'includes/messages.html' %}

    <div class="border rounded text-center p-3 m-3 bg_light shadow">
        {% block header %}
            <h2>Welcome to LMS</h2>
        {% endblock %}
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}


{% endblock %}